# Generated by Django 5.1.2 on 2024-10-30 12:40

from django.db import migrations

# This will always be a local project, so who cares if you can see this
def generate_superuser(apps, schema_editor):
    from django.contrib.auth.models import User
    DJANGO_SU_NAME = 'test'
    DJANGO_SU_EMAIL = 'test@test.com'
    DJANGO_SU_PASSWORD = 'test'

    superuser = User.objects.create_superuser(
        username=DJANGO_SU_NAME,
        email=DJANGO_SU_EMAIL,
        password=DJANGO_SU_PASSWORD
    )
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(generate_superuser),
    ]